import Footer from './components/Footer'
import Navbar from './components/Navbar'
import './globals.css'
import { Nunito_Sans } from 'next/font/google'


const nunito_sans = Nunito_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'MyWeather',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <link rel="icon" href="./app-logo.png" />
      <body className={nunito_sans.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
